export const clientList = [
  "360 Vodka",
  "ABF Group",
  "AIKU LABS LTD",
  "Aagrah",
  "Aber Falls",
  "Absolut",
  "Absolut & Sprite",
  "ActiSnack",
  "Ainsley Harriot",
  "Al'Fez",
  "Aleyna",
  "All the Aunties Paneer",
  "All things Butter & Cottage Cheese",
  "Alter ego cottage cheese",
  "Amaretto",
  "Amoy",
  "Andrew Peace",
  "Angelic Free From",
  "Annabel Karmel",
  "Aqua Carpatica",
  "Arctic Coffee",
  "Askey's",
  "Aspall",
  "BLUEBERRY HILL MEALS LIMITED",
  "BOL",
  "BOSH!",
  "Bahlsen",
  "Baker Street",
  "Bandero Tequila",
  "Bankhall",
  "Barilla",
  "Beefeater",
  "Belazu",
  "Bello Artizano",
  "Belvoir",
  "Bepps",
  "Beronia",
  "Bertolli",
  "Biff Plant",
  "Biff's",
  "Bigham",
  "Billington",
  "Bio & Me",
  "Bio and Me",
  "Blanco Nino",
  "Blue Dragon",
  "Boissy & Delaygue",
  "Bold Bean Co",
  "Bonne Maman Spreads & Desserts",
  "Bonne maman Biscuits & Cakes",
  "Borough Broth",
  "Brave Snacks",
  "Bromptons",
  "Brut Dargent",
  "Buderim",
  "Buiteman",
  "By Ruby",
  "Cadbury",
  "Café Pod",
  "Calvet",
  "Capsicana",
  "Cardini's",
  "Carling",
  "Cathedral City",
  "Cellier des Dauphins",
  "Chavroux",
  "Cheesies",
  "Chivas Regal",
  "Chupa",
  "Château de l’Estagnol",
  "Cirio",
  "Clarks maple syrup",
  "CleanCo",
  "Cobra",
  "Coconut Merchant",
  "Cooks & Co",
  "Coors",
  "Costa Drinks",
  "Costa Salt",
  "Cotswolds",
  "Crazy Jack",
  "Cricket St Thomas",
  "Croft Original",
  "Crosta & Mollica",
  "Cypressa",
  "Dame",
  "Dash Water",
  "Days Brewing",
  "Dead Mans Finger",
  "Defiant Ones UK LTD",
  "Del Monte",
  "Delamere",
  "Delicious Desserts",
  "Deliciously Ella",
  "Dickinson & Morris",
  "Disaronno",
  "Dishmatic",
  "Doom Bar",
  "Dorset Cereals",
  "Dot Dot Bubble Tea",
  "Double Dutch",
  "Doughlicious",
  "Douwe Egberts",
  "Dozz cold soup",
  "Dr Beckmann",
  "Dr Funk",
  "Dr Schar",
  "Dr Squatch",
  "Dr Wills",
  "Dre and Snoop Still G.I.N.",
  "Duerrs",
  "Dunkin",
  "Dutch Barn Vodka",
  "E&J Gallo",
  "Eat Real",
  "Elephant Atta",
  "Elizabeth Shaw",
  "Ella’s Kitchen baby food",
  "Ellers Farm Distillery (Dutch Barn Vodka)",
  "Ellers Farm Distillery Ltd",
  "Ember Snacks",
  "Emmi",
  "Engine Gin",
  "Engine Oil",
  "English Cheesecake",
  "English Cheesecake Company",
  "Euro Food Brands (Ireland)",
  "Everleaf",
  "Exalt",
  "Fairtrade LTD - food thoughts",
  "Fearne & Rosie Jam",
  "Fellow Creatures Ltd",
  "Fentimans",
  "Fevertree",
  "Fibe",
  "Fish 4 Ever",
  "Fitbakes",
  "Fix8",
  "Fleurs de Prairie",
  "Flo",
  "Flower Farm - not listed in UK anymore",
  "Flower of Life Ltd",
  "Foraging Fox",
  "Forest Feast",
  "Forthglade",
  "Four Five Hydration",
  "Fox's",
  "Freddies",
  "Freja Stock",
  "Fruit Bowl",
  "Fruity Pot",
  "Fullgreen",
  "FunkIn",
  "GOOD PHATS",
  "Gail's",
  "Galbani",
  "Galloway",
  "Galuval",
  "Get More Vits",
  "Ginsters",
  "Golden Wonder",
  "Goodies",
  "Goodness Shakes",
  "Gran Luchito",
  "Grand Sud",
  "Green Dragon",
  "Grey Poupon",
  "Grind",
  "Grounded",
  "Grumpy Mule",
  "Gymkhana",
  "HIDE",
  "HIP chocolate",
  "Halo Top",
  "Happy Snax",
  "Happy Tuesday's",
  "Hartley’s jam",
  "Havana Club",
  "Heinz",
  "Hermestas",
  "Hershey",
  "Hershey Desserts",
  "Hersheys",
  "Hi Life",
  "Higgidy",
  "Highland Spring",
  "Hilltop",
  "Hip Pop",
  "Hippeas",
  "Hiver",
  "Hollings",
  "Holos Kombucha",
  "Holy Moly",
  "Howdah Snacks",
  "Hu Chocolate",
  "Huel",
  "Humantra hydtration",
  "Hunt & Brew",
  "Illy",
  "Indogulf Bioag",
  "Innocent",
  "Innvoviom Inc",
  "Insane Grain",
  "Irn Bru",
  "Itsu",
  "J.P. Chenet",
  "JJ Whitely",
  "Jack & Bry",
  "Jack & Coke",
  "Jacksons",
  "Jake & Nayns",
  "Jameson",
  "Jammie",
  "Jeera",
  "Jelly Squeeze",
  "Jordans",
  "Jungle Squad",
  "KENDAL NUTRICARE LTD",
  "KIND",
  "Karma",
  "Kelloggs",
  "Kelly's",
  "Kenco",
  "Kikkoman",
  "Kirsty's",
  "Kitchen Joy",
  "Kohinoor",
  "Koppaberg",
  "Kulcher",
  "L'Or",
  "LEAP",
  "LVK GLOBAL LTD",
  "La Drogheria",
  "La Vie",
  "Las Chicas",
  "Lavazza",
  "Lazy Joe Oats",
  "Lazy Vegan",
  "Le Rustique",
  "Leerdammer",
  "Les Dauphins (retro-style)",
  "Levi Roots",
  "Lily O'Briens",
  "Linda McCartney’s meat-free products",
  "Listed in  H&B",
  "Little Freddie",
  "Little Moons",
  "Living Things",
  "Lizi",
  "Lone Wolf",
  "Lottie Shaw",
  "Love Corn",
  "Love Sum",
  "Luchito",
  "Lucozade",
  "Lune & wild",
  "MISSION Health & Wellness Ltd",
  "MOROCCAN AND YUMMY LTD",
  "Madri",
  "Mahi",
  "Malfy",
  "Malibu",
  "Manilife",
  "Marmite Crisps",
  "Mary Berry",
  "Maryland",
  "Mazzetti",
  "McCain",
  "Meica",
  "Mentos",
  "Merchant Gourmet",
  "Midland Snacks",
  "Minor Figures",
  "Misfits",
  "Mister Freed",
  "Modern Nature Ltd",
  "Moju",
  "Moma",
  "Monkey 47",
  "Moo",
  "Moorish",
  "More Toddler Meals",
  "Moth",
  "Mother Root",
  "Mowi",
  "Mr Porky's",
  "Munch Bunch",
  "Mutti",
  "My Protein",
  "My Pura Nappies & Wipes",
  "N/A - Craig Hughes",
  "NIMBLE BABIES LIMITED",
  "NOW PART OF AG BARR",
  "NTSAMA CHILLI OIL AND SAUCES LIMITED",
  "NUTMEG AND HIVE",
  "Naked Paper Toilet rolls",
  "Natural Days",
  "Neat Home",
  "Ned",
  "New Covent Garden Soup Co.",
  "New England",
  "Nexba",
  "Nice Rice",
  "Nice Wine",
  "Niru",
  "Nix & Kix",
  "Nozecco",
  "Nuii",
  "O/L",
  "OATO",
  "Ocean Spray",
  "Oddbox",
  "Oddlygood",
  "Oddlygood UK LTD",
  "Oggs",
  "Old El Paso Meals",
  "Olly's",
  "One Gin",
  "One Water",
  "Onken",
  "Oppo Ice Cream",
  "Orangina",
  "Oreo",
  "Organix",
  "Orkney PGI",
  "Otsu",
  "PART OF McCAINS",
  "PIMENTA LTD",
  "Pack'd",
  "Papa Salt",
  "Pasta Evangelists",
  "Pataks",
  "Patersons",
  "Patum Peperium",
  "Peppadew",
  "Perrier-Jouët.",
  "Phizz Hydration",
  "Picard",
  "Piccolo",
  "Pinch",
  "Pizza Express",
  "Planted (meats)",
  "Plants",
  "Pollen + Grace",
  "Positive Science People",
  "Pringles",
  "Product Chain",
  "Project Nootropic Ltd",
  "Proper",
  "Président",
  "Pukka",
  "Purely Plantain / OHSO - Amazon & Ocado",
  "Quaker",
  "Quinola",
  "RENTBRELLA UK LTD",
  "Rachel's Organic",
  "Raise Snacks",
  "Rajah",
  "Reacock salt & water softners",
  "Real Pork Scratching",
  "Realfoods",
  "Reese's desserts",
  "Reeses",
  "Rekorderlig",
  "Remeo",
  "Rheal",
  "Ribena",
  "Rish Right",
  "Rock Face",
  "Rodda",
  "Rosewood",
  "Rowntree",
  "Rubicon",
  "Rude Health",
  "Ryvita",
  "SKINNYDIP LIMITED",
  "Sabor de Amor Limited",
  "Saint Agur",
  "Sanchi",
  "Sapling Vodka",
  "Sauce Shop",
  "Savyll",
  "Scrapples",
  "Seafood & Eat It",
  "Seep",
  "Selecta UK",
  "Seriously® Strong Cheddar",
  "Served",
  "Shady Mapel",
  "Sharp's",
  "Shires Bakery",
  "Silverspoon",
  "Simply Donuts",
  "Simply Nibbles",
  "Sipsmith",
  "Smart Strains",
  "Smile Science",
  "Smint & Fruitella",
  "Snaffling Pig",
  "Soda Folk",
  "Soulfresh",
  "Soupologie Limited",
  "Spare Snacks",
  "Spoon",
  "Spooners",
  "St Michel",
  "St Pierre",
  "Staropramen",
  "Sun-Pat peanut butter",
  "Sunny & Luna",
  "Superbake",
  "Surreal",
  "Sweet Baby Rays BBQ Sauce",
  "Tabasco",
  "Tamari",
  "Tarantella Organic",
  "Tarquins Gin",
  "Tassimo",
  "Taste Inc",
  "Tayto",
  "Tesco Finest Pizza",
  "Tesco Sausages (OL)",
  "The Busker",
  "The Cheeky Panda Limited",
  "The Coconut Collab",
  "The Collective Dairy",
  "The Curators",
  "The Flan Co",
  "The Glenlivet",
  "The Gym Kitchen",
  "The Online Tasting Company Ltd",
  "The Soho Juice Co",
  "The nu company GmbH",
  "Thingies",
  "Thomas Fudges",
  "Tia Maria",
  "Tideford Organics",
  "Tild Rice",
  "TimTams",
  "Tims Yogurt & Kifr",
  "Tio Pepe",
  "Toasteez",
  "Tohfa",
  "Tonic Health",
  "Tribe",
  "Trinsic",
  "Trip",
  "Triple Diamond",
  "Trophy",
  "TrueStart",
  "Twin Fin Rum",
  "Two Chicks",
  "Tyiba Tempeh",
  "UFC",
  "UFit",
  "Unbeleafable",
  "Unearthed",
  "Unfabled Ltd",
  "Unrooted Drinks",
  "Up & Go",
  "VOW Protein drinks",
  "Vignerons de l’Enclave",
  "Vilarnau",
  "Virtue",
  "Vita Coco",
  "Vitacore",
  "Vitalin",
  "Vitl",
  "Vivid Vitality Ltd",
  "WILD",
  "Waffle Amour",
  "Wagon Wheels",
  "Wahoo! la boulangere",
  "Walkers",
  "Watbeck Limited",
  "When in Rome",
  "Whitby Seafoods",
  "White Rabbit",
  "Whitley Neill",
  "Wild Thingz",
  "Wildfarmed Bread",
  "Willy's",
  "Wirra Wirra",
  "Wotsit Meals",
  "XO!",
  "XP Brands Ltd",
  "Yeo Valley",
  "Yo Po",
  "Zombie snacks",
  "Zooki",
  "Åguas Minerales de Avila"
];
